version: '3.8'
services:
  api:
    build: .
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/ecommerce-db
      - JWT_SECRET=your_production_secret
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_SECRET=your_production_refresh_secret
      - JWT_REFRESH_EXPIRES_IN=7d
      - CORS_ORIGIN=https://your-frontend-domain.com
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: